#!/bin/bash
set -euo pipefail

apt update
apt -o DPkg::Options::=--force-confdef install -y procps jq wget zsh tmux curl ca-certificates musl-tools

wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O /tmp/install-omz.sh && zsh /tmp/install-omz.sh --unattended || true

cd ~
tmux kill-server
git clone --single-branch https://github.com/gpakosz/.tmux.git
ln -s -f .tmux/.tmux.conf

cd /app
cp .devcontainer/.tmux.conf ~/.tmux.conf.local

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
. "$HOME/.cargo/env"
rustup component add clippy rustfmt
cargo install cargo-watch

apt install -y postgresql-client

curl -fsSL https://claude.ai/install.sh | bash
echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.zshrc && source ~/.zshrc
echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> ~/.zshrc && source ~/.zshrc
