services:
  app:
    image: ghcr.io/${ORGANIZATION}/${PROJECT}:latest
    build:
      context: .
      target: app
      secrets:
        - github_token
      args:
        ORGANIZATION: ${ORGANIZATION}
      cache_from:
        - type=registry,ref=ghcr.io/${ORGANIZATION:-slivern-corporate-services}/${PROJECT:-forma}:buildcache
    volumes:
      - .:/app

secrets:
  github_token:
    environment: GITHUB_TOKEN
