services:
  app:
    entrypoint: ["sleep"]
    command: ["infinity"]
    build:
      context: ..
      dockerfile: Dockerfile
      target: base
      secrets:
        - github_token
      args:
        ORGANIZATION: ${ORGANIZATION:-slivern-corporate-services}
    env_file:
      - ../.env
    volumes:
      - ..:/app

secrets:
  github_token:
    environment: GITHUB_TOKEN
