name: Build

on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_ORG_REPO_READ || github.token }}
          submodules: true

      - name: Checkout ${{ github.repository_owner }}/opv-actions
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/opv-actions
          ref: v3
          token: ${{ secrets.PAT_ORG_REPO_READ || github.token }}
          path: .opv-actions

      - name: Run build
        uses: ./.opv-actions
        with:
          badges-token:            ${{ secrets.PAT_BADGES }}
          repositories-read-token: ${{ secrets.PAT_ORG_REPO_READ }}
